Expence Tracker/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Expence_Tracker.Models;

namespace Expence_Tracker.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
              return _context.Category != null ? 
                          View(await _context.Category.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Category'  is null.");
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Category == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/CreateOrEdit
        public IActionResult CreateOrEdit(int id=0)
        {
            if (id == 0)
            {

            return View(new Category());
            }
            else
            {
                return View(_context.Category.Find(id));

            }

        }

        // POST: Categories/CreateOrEdit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOrEdit([Bind("CategoryId,Title,Icon,Type")] Category category)
        {
            if (ModelState.IsValid)
            {
                if(category.CategoryId== 0)
                {
                _context.Add(category);
                }
                else
                {
                    _context.Update(category);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        #region Update
        // GET: Categories/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null || _context.Category == null)
        //    {
        //        return NotFound();
        //    }

        //    var category = await _context.Category.FindAsync(id);
        //    if (category == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(category);
        //}

        //// POST: Categories/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("CategoryId,Title,Icon,Type")] Category category)
        //{
        //    if (id != category.CategoryId)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(category);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!CategoryExists(category.CategoryId))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(category);
        //}

        #endregion

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Category == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Category == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Category'  is null.");
            }
            var category = await _context.Category.FindAsync(id);
            if (category != null)
            {
                _context.Category.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Category?.Any(e => e.CategoryId == id)).GetValueOrDefault();
        }
    }
}

Expence Tracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Expence Tracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/25.1.35/material.css" />*@
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/25.1.35/bootstrap5-dark.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/Expence_Tracker.styles.css" asp-append-version="true" />*@
    <script src="https://cdn.syncfusion.com/ej2/25.1.35/dist/ej2.min.js"></script>
</head>
<body class="e-bigger">
    <partial name="_Sidebar"/>
    <nav class="navbar sticky-top navbar-light">
        <div class="container-fluid py-2 px-4">
            <i class="fa-solid fa-magnifying-glass"></i>
            <div>
                <i class="fa-solid fa-bell"></i>
                <i class="fa-solid fa-message"></i>
                <img class="profile-pic" src="~/profile-pic.jpg"/>
            </div>
        </div>
    </nav>
    <div class="main-content">
    <div class="container mt-5">
        <div class="row justify-content-center">
                <div class="@(ViewData["isDashboead"] == null?"col-md-10":"col-md-12")">
                <main role="main" class="pb-3">
                        @if (ViewData["isDashboead"] == null)
                        {
                            <div class="row">
                                <div class="col-md-7">
                                    <div class="d-flex flex-column mb-5">
                                        <div class="d-flex mb-1">
                                            <div class="flex-grow-1">
                                                <h3 class="fw-bold">@ViewData["PageTitle"]</h3>
                                            </div>
                                            <div>
                                                @if (@ViewData["PageActionText"] != null)
                                                {
                                                    <a class="btn btn-success" href="@ViewData["PageActionUrl"]">
                                                        @ViewData["PageActionText"]
                                                    </a>
                                                }
                                            </div>
                                        </div>
                                        <ejs-breadcrumb id="breadcrumb"
                                                    separatorTemplate="@Html.Raw("<span class='fa-solid fa-angle-right'></span>")"></ejs-breadcrumb>
                                    </div>
                                </div>
                            </div>
                        }
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <ejs-scripts></ejs-scripts>
</body>
</html>

Expence Tracker/Views/Shared/_Sidebar.cshtml
@{
	List<object> menuItems = new List<object>();

	menuItems.Add(new
	{
		text = "Genarel",
		separetor=true
	});
	menuItems.Add(new
	{
		text = "Dashboard",
		url = "/",
		iconCss = "fa-solid fa-box"
	});
	menuItems.Add(new
	{
		text = "Category",
		url = Url.Action("Index", "Categories"),
		iconCss="fa-solid fa-folder-closed"
	});
	menuItems.Add(new
	{
		text = "Transactions",
		url = Url.Action("Index", "Transactions"),
		iconCss="fa-solid fa-arrow-right-arrow-left"
	});
	menuItems.Add(new
	{
		text = "Extras",
		separetor=true
	});
	menuItems.Add(new
	{
		text = "Reports",
		url = "#",
		iconCss="fa-solid fa-chart-simple"
	});
	menuItems.Add(new
	{
		text = "Settings",
		url = "#",
		iconCss = "fa-solid fa-gear"
	});
}
<!-- sidebar element declaration -->
<ejs-sidebar id="sidebar" width="290px" closeOnDocumentClick="false">
	
	<e-content-template>
		<div class="logo-wrapper">
			<div class="app-logo">
				<img  src="~/favicon-32x32.png"/>
			</div>
			<div class="w-100"></div>
			<i id="sidebar-toggler" class="fa-solid fa-angles-left"></i>
		</div>
		<div class="profile-wrapper">
			<img class="profile-pic" src="~/profile-pic.jpg"/>
			<div class="titles d-flex flex-column ps-3">
				<h6 class="mb-0">Wallet App</h6>
				<span class="text-muted">Shiba Sarkar</span>
			</div>
		</div>
		<ejs-menu id="menu" items="menuItems" orientation="Vertical"></ejs-menu>
	</e-content-template>
</ejs-sidebar>
<!-- end of sidebar element -->
@section Scripts{
	<script>
		$(document).ready(function () {
			var dockBar = $('sidebar').ej2_instances[0].val();
			$('sidebar-toggler').on('click',function(){
				dockBar.toggle();
			});
		});
	</script>
}

Expence Tracker/Views/Shared/_exmp.cshtml
<div>
    <h1>Hello World !!</h1>
</div>